<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VerbsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('verbs')->insert([
          ['verb'=>'accept', 'past'=>'accepted', 'participle'=>'accepted', 'gerund'=>'accepting','meaning'=>'aceptar'],
['verb'=>'answer', 'past'=>'answered', 'participle'=>'answered', 'gerund'=>'answering','meaning'=>'contestar'],
['verb'=>'arrive', 'past'=>'arrived', 'participle'=>'arrived', 'gerund'=>'arriving','meaning'=>'llegar'],
['verb'=>'ask', 'past'=>'asked', 'participle'=>'asked', 'gerund'=>'asking','meaning'=>'preguntar'],
['verb'=>'belong', 'past'=>'belonged', 'participle'=>'belonged', 'gerund'=>'belonging','meaning'=>'pertenecer'],
['verb'=>'change', 'past'=>'changed', 'participle'=>'changed', 'gerund'=>'changing','meaning'=>'cambiar'],
['verb'=>'clean', 'past'=>'cleaned', 'participle'=>'cleaned', 'gerund'=>'cleaning','meaning'=>'limpiar'],
['verb'=>'climb', 'past'=>'climbed', 'participle'=>'climbed', 'gerund'=>'climbing','meaning'=>'trepar'],
['verb'=>'close', 'past'=>'closed', 'participle'=>'closed', 'gerund'=>'closing','meaning'=>'cerrar'],
['verb'=>'consider', 'past'=>'considered', 'participle'=>'considered', 'gerund'=>'considering','meaning'=>'considerar'],
['verb'=>'cook', 'past'=>'cooked', 'participle'=>'cooked', 'gerund'=>'cooking','meaning'=>'cocinar'],
['verb'=>'count', 'past'=>'counted', 'participle'=>'counted', 'gerund'=>'couting','meaning'=>'contar'],
['verb'=>'dance', 'past'=>'danced', 'participle'=>'danced', 'gerund'=>'dancing','meaning'=>'bailar'],
['verb'=>'dare', 'past'=>'dared', 'participle'=>'dared', 'gerund'=>'daring','meaning'=>'atreverse'],
['verb'=>'date', 'past'=>'dated', 'participle'=>'dated', 'gerund'=>'dating','meaning'=>'citar'],
['verb'=>'deliver', 'past'=>'delivered', 'participle'=>'delivered', 'gerund'=>'delivering','meaning'=>'entregar'],
['verb'=>'dress', 'past'=>'dressed', 'participle'=>'dressed', 'gerund'=>'dressing','meaning'=>'vestir'],
['verb'=>'end', 'past'=>'ended', 'participle'=>'ended', 'gerund'=>'ending','meaning'=>'terminar'],
['verb'=>'enjoy', 'past'=>'enjoyed', 'participle'=>'enjoyed', 'gerund'=>'enjoying','meaning'=>'gozar'],
['verb'=>'erase', 'past'=>'erased', 'participle'=>'erased', 'gerund'=>'erasing','meaning'=>'borrar'],
['verb'=>'expect', 'past'=>'expected', 'participle'=>'expected', 'gerund'=>'expecting','meaning'=>'esperar'],
['verb'=>'fill', 'past'=>'filled', 'participle'=>'filled', 'gerund'=>'filling','meaning'=>'llenar'],
['verb'=>'finish', 'past'=>'finished', 'participle'=>'finished', 'gerund'=>'finishing','meaning'=>'terminar'],
['verb'=>'follow', 'past'=>'followed', 'participle'=>'followed', 'gerund'=>'following','meaning'=>'seguir'],
['verb'=>'help', 'past'=>'helped', 'participle'=>'helped', 'gerund'=>'helping','meaning'=>'ayudar'],
['verb'=>'hurry', 'past'=>'hurried', 'participle'=>'hurried', 'gerund'=>'hurrying','meaning'=>'apresurarse'],
['verb'=>'intend', 'past'=>'intended', 'participle'=>'intended', 'gerund'=>'intending','meaning'=>'intentar'],
['verb'=>'jump', 'past'=>'jumped', 'participle'=>'jumped', 'gerund'=>'jumping','meaning'=>'brincar'],
['verb'=>'learn', 'past'=>'learned', 'participle'=>'learned', 'gerund'=>'learning','meaning'=>'aprender'],
['verb'=>'like', 'past'=>'liked', 'participle'=>'liked', 'gerund'=>'liking','meaning'=>'gustar'],
['verb'=>'listen', 'past'=>'listened', 'participle'=>'listened', 'gerund'=>'listening','meaning'=>'escuchar'],
['verb'=>'live', 'past'=>'lived', 'participle'=>'lived', 'gerund'=>'living','meaning'=>'vivir'],
['verb'=>'look', 'past'=>'looked', 'participle'=>'looked', 'gerund'=>'looking','meaning'=>'mirar'],
['verb'=>'love', 'past'=>'loved', 'participle'=>'loved', 'gerund'=>'loving','meaning'=>'amar'],
['verb'=>'miss', 'past'=>'missed', 'participle'=>'missed', 'gerund'=>'missing','meaning'=>'extrañar'],
['verb'=>'name', 'past'=>'named', 'participle'=>'named', 'gerund'=>'naming','meaning'=>'llamar'],
['verb'=>'need', 'past'=>'needed', 'participle'=>'needed', 'gerund'=>'needing','meaning'=>'necesitar'],
['verb'=>'open', 'past'=>'opened', 'participle'=>'opened', 'gerund'=>'opening','meaning'=>'abrir'],
['verb'=>'order', 'past'=>'ordered', 'participle'=>'ordered', 'gerund'=>'ordening','meaning'=>'ordenar'],
['verb'=>'plan', 'past'=>'planned', 'participle'=>'planned', 'gerund'=>'plannig','meaning'=>'planear'],
['verb'=>'plant', 'past'=>'planted', 'participle'=>'planted', 'gerund'=>'planting','meaning'=>'plantar'],
['verb'=>'play', 'past'=>'played', 'participle'=>'played', 'gerund'=>'playing','meaning'=>'jugar'],
['verb'=>'point', 'past'=>'pointed', 'participle'=>'pointed', 'gerund'=>'pointing','meaning'=>'señalar'],
['verb'=>'practice', 'past'=>'practiced', 'participle'=>'practiced', 'gerund'=>'practicing','meaning'=>'practicar'],
['verb'=>'push', 'past'=>'pushed', 'participle'=>'pushed', 'gerund'=>'pushing','meaning'=>'empujar'],
['verb'=>'rain', 'past'=>'rained', 'participle'=>'rained', 'gerund'=>'raining','meaning'=>'llover'],
['verb'=>'remember', 'past'=>'remembered', 'participle'=>'remembered', 'gerund'=>'remembering','meaning'=>'recordar'],
['verb'=>'rent', 'past'=>'rented', 'participle'=>'rented', 'gerund'=>'renting','meaning'=>'alquilar'],
['verb'=>'repeat', 'past'=>'repeated', 'participle'=>'repeated', 'gerund'=>'repeating','meaning'=>'repetir'],
['verb'=>'resist', 'past'=>'resisted', 'participle'=>'resisted', 'gerund'=>'resisting','meaning'=>'resistir'],
['verb'=>'show', 'past'=>'showed', 'participle'=>'showed', 'gerund'=>'showing','meaning'=>'mostrar'],
['verb'=>'smoke', 'past'=>'smoked', 'participle'=>'smoking', 'gerund'=>'smoking','meaning'=>'fumar'],
['verb'=>'start', 'past'=>'started', 'participle'=>'started', 'gerund'=>'starting','meaning'=>'empezar'],
['verb'=>'stay', 'past'=>'stayed', 'participle'=>'stayed', 'gerund'=>'staying','meaning'=>'permanecer'],
['verb'=>'stop', 'past'=>'stopped', 'participle'=>'stopped', 'gerund'=>'stopping','meaning'=>'parar'],
['verb'=>'study', 'past'=>'studied', 'participle'=>'studied', 'gerund'=>'studying','meaning'=>'estudiar'],
['verb'=>'talk', 'past'=>'talked', 'participle'=>'talked', 'gerund'=>'talking','meaning'=>'hablar'],
['verb'=>'travel', 'past'=>'traveled', 'participle'=>'traveled', 'gerund'=>'traveling','meaning'=>'viajar'],
['verb'=>'try', 'past'=>'tried', 'participle'=>'tried', 'gerund'=>'trying','meaning'=>'intentar'],
['verb'=>'turn', 'past'=>'turned', 'participle'=>'turned', 'gerund'=>'turning','meaning'=>'voltear'],
['verb'=>'use', 'past'=>'used', 'participle'=>'used', 'gerund'=>'using','meaning'=>'usar'],
['verb'=>'visit', 'past'=>'visited', 'participle'=>'visited', 'gerund'=>'visiting','meaning'=>'visitar'],
['verb'=>'wait', 'past'=>'waited', 'participle'=>'waited', 'gerund'=>'waiting','meaning'=>'esperar'],
['verb'=>'walk', 'past'=>'walked', 'participle'=>'walked', 'gerund'=>'walking','meaning'=>'caminar'],
['verb'=>'want', 'past'=>'wanted', 'participle'=>'wanted', 'gerund'=>'wanting','meaning'=>'querer'],
['verb'=>'wash', 'past'=>'washed', 'participle'=>'washed', 'gerund'=>'washing','meaning'=>'lavar'],
['verb'=>'wish', 'past'=>'wished', 'participle'=>'wished', 'gerund'=>'wishing','meaning'=>'desear'],
['verb'=>'work', 'past'=>'worked', 'participle'=>'worked', 'gerund'=>'working','meaning'=>'trabajar'],
['verb'=>'bake', 'past'=>'baked', 'participle'=>'baked', 'gerund'=>'baking','meaning'=>'hornear'],
['verb'=>'ban', 'past'=>'banned', 'participle'=>'banned', 'gerund'=>'banning','meaning'=>'prohivir'],
['verb'=>'boil', 'past'=>'boiled', 'participle'=>'boiled', 'gerund'=>'boiling','meaning'=>'hervir'],
['verb'=>'beg', 'past'=>'begged', 'participle'=>'begged', 'gerund'=>'begging','meaning'=>'rogar'],
['verb'=>'blush', 'past'=>'blushed', 'participle'=>'blushed', 'gerund'=>'blushing','meaning'=>'sonrojarse'],
['verb'=>'call', 'past'=>'called', 'participle'=>'called', 'gerund'=>'calling','meaning'=>'llamar'],
['verb'=>'care', 'past'=>'cared', 'participle'=>'cared', 'gerund'=>'caring','meaning'=>'preocuparse'],
['verb'=>'chew', 'past'=>'chewed', 'participle'=>'chewed', 'gerund'=>'chewing','meaning'=>'mascar'],
['verb'=>'choke', 'past'=>'choked', 'participle'=>'choked', 'gerund'=>'choking','meaning'=>'ahogar'],
['verb'=>'coach', 'past'=>'coached', 'participle'=>'coached', 'gerund'=>'coaching','meaning'=>'entrenar'],
['verb'=>'cough', 'past'=>'coughed', 'participle'=>'coughed', 'gerund'=>'coughing','meaning'=>'toser'],
['verb'=>'deserve', 'past'=>'deserved', 'participle'=>'deserved', 'gerund'=>'deserving','meaning'=>'merecer'],
['verb'=>'disagree', 'past'=>'disagreed', 'participle'=>'disagreed', 'gerund'=>'disagreeing','meaning'=>'estar en desacuerdo'],
['verb'=>'earn', 'past'=>'earned', 'participle'=>'earned', 'gerund'=>'earning','meaning'=>'ganar'],
['verb'=>'excite', 'past'=>'excited', 'participle'=>'excited', 'gerund'=>'exciting','meaning'=>'emocionarse'],
['verb'=>'embarrass', 'past'=>'embarrassed', 'participle'=>'embarrassed', 'gerund'=>'embarrassing','meaning'=>'avergonzar'],
['verb'=>'face', 'past'=>'faced', 'participle'=>'faced', 'gerund'=>'facing','meaning'=>'encarar'],
['verb'=>'fancy', 'past'=>'fancied', 'participle'=>'fancied', 'gerund'=>'fancying','meaning'=>'tener ganas'],
['verb'=>'fix', 'past'=>'fixed', 'participle'=>'fixed', 'gerund'=>'fixing','meaning'=>'reparar'],
['verb'=>'force', 'past'=>'forced', 'participle'=>'forced', 'gerund'=>'forcing','meaning'=>'forzar'],
['verb'=>'gather', 'past'=>'gathered', 'participle'=>'gathered', 'gerund'=>'gathering','meaning'=>'reunir'],
['verb'=>'grab', 'past'=>'grabbed', 'participle'=>'grabbed', 'gerund'=>'grabbing','meaning'=>'agarrar'],
['verb'=>'greet', 'past'=>'greeted', 'participle'=>'greeted', 'gerund'=>'greeting','meaning'=>'saludar'],
['verb'=>'guarantee', 'past'=>'guaranteed', 'participle'=>'guaranteed', 'gerund'=>'guaranteeing','meaning'=>'garantizar'],
['verb'=>'hand', 'past'=>'handed', 'participle'=>'handed', 'gerund'=>'handing','meaning'=>'dar'],
['verb'=>'happen', 'past'=>'happened', 'participle'=>'happened', 'gerund'=>'happening','meaning'=>'pasar'],
['verb'=>'harass', 'past'=>'harassed', 'participle'=>'harassed', 'gerund'=>'harassing','meaning'=>'acosar'],
['verb'=>'improve', 'past'=>'improved', 'participle'=>'improved', 'gerund'=>'improving','meaning'=>'mejorar'],
['verb'=>'cost', 'past'=>'cost', 'participle'=>'cost', 'gerund'=>'costing','meaning'=>'costar'],
['verb'=>'cut', 'past'=>'cut', 'participle'=>'cut', 'gerund'=>'cutting','meaning'=>'cortar'],
['verb'=>'fit', 'past'=>'fit', 'participle'=>'fit', 'gerund'=>'fitting','meaning'=>'quedar'],
['verb'=>'hit', 'past'=>'ht', 'participle'=>'hit', 'gerund'=>'hitting','meaning'=>'golpear'],
['verb'=>'hurt', 'past'=>'hurt', 'participle'=>'hurt', 'gerund'=>'hurting','meaning'=>'lastimar'],
['verb'=>'let', 'past'=>'let', 'participle'=>'let', 'gerund'=>'letting','meaning'=>'permitir'],
['verb'=>'put', 'past'=>'put', 'participle'=>'put', 'gerund'=>'putting','meaning'=>'poner'],
['verb'=>'quit', 'past'=>'quit', 'participle'=>'quit', 'gerund'=>'quitting','meaning'=>'dejar'],
['verb'=>'set', 'past'=>'set', 'participle'=>'set', 'gerund'=>'setting','meaning'=>'poner'],
['verb'=>'become', 'past'=>'became', 'participle'=>'become', 'gerund'=>'becoming','meaning'=>'llegar a ser'],
['verb'=>'come', 'past'=>'came', 'participle'=>'come', 'gerund'=>'coming','meaning'=>'venir'],
['verb'=>'run', 'past'=>'ran', 'participle'=>'run', 'gerund'=>'running','meaning'=>'correr'],
['verb'=>'begin', 'past'=>'began', 'participle'=>'begun', 'gerund'=>'beginning','meaning'=>'comenzar'],
['verb'=>'drink', 'past'=>'drank', 'participle'=>'drunk', 'gerund'=>'drinking','meaning'=>'beber'],
['verb'=>'ring', 'past'=>'rang', 'participle'=>'rung', 'gerund'=>'ringing','meaning'=>'sonar'],
['verb'=>'shrink', 'past'=>'shrank', 'participle'=>'shrunk', 'gerund'=>'shrinking','meaning'=>'encoger'],
['verb'=>'sing', 'past'=>'sang', 'participle'=>'sung', 'gerund'=>'singing','meaning'=>'cantar'],
['verb'=>'swim', 'past'=>'swam', 'participle'=>'swum', 'gerund'=>'swimming','meaning'=>'nadar'],
['verb'=>'blow', 'past'=>'blew', 'participle'=>'blown', 'gerund'=>'blowing','meaning'=>'soplar'],
['verb'=>'draw', 'past'=>'drew', 'participle'=>'drawn', 'gerund'=>'drawing','meaning'=>'dibujar'],
['verb'=>'fly', 'past'=>'flew', 'participle'=>'flown', 'gerund'=>'flying','meaning'=>'volar'],
['verb'=>'grow up', 'past'=>'grew up', 'participle'=>'grown up', 'gerund'=>'growing up','meaning'=>'crecer'],
['verb'=>'know', 'past'=>'knew', 'participle'=>'known', 'gerund'=>'knowing','meaning'=>'saber'],
['verb'=>'throw', 'past'=>'threw', 'participle'=>'thrown', 'gerund'=>'throwing','meaning'=>'tirar'],
['verb'=>'withdraw', 'past'=>'withdrew', 'participle'=>'withdrawn', 'gerund'=>'withdrawing','meaning'=>'retirar'],
['verb'=>'bring', 'past'=>'brought', 'participle'=>'brought', 'gerund'=>'bringing','meaning'=>'traer'],
['verb'=>'buy', 'past'=>'bought', 'participle'=>'bought', 'gerund'=>'buying','meaning'=>'comprar'],
['verb'=>'catch', 'past'=>'caught', 'participle'=>'caught', 'gerund'=>'catching','meaning'=>'atrapar'],
['verb'=>'fight', 'past'=>'fought', 'participle'=>'fought', 'gerund'=>'fighting','meaning'=>'pelear'],
['verb'=>'teach', 'past'=>'taught', 'participle'=>'taught', 'gerund'=>'teaching','meaning'=>'enseñar'],
['verb'=>'think', 'past'=>'thought', 'participle'=>'thought', 'gerund'=>'thinking','meaning'=>'pensar'],
['verb'=>'bite', 'past'=>'bit', 'participle'=>'bitten', 'gerund'=>'biting','meaning'=>'morder'],
['verb'=>'break', 'past'=>'broke', 'participle'=>'broken', 'gerund'=>'breaking','meaning'=>'romper'],
['verb'=>'choose', 'past'=>'chose', 'participle'=>'chosen', 'gerund'=>'choosing','meaning'=>'escoger'],
['verb'=>'drive', 'past'=>'drove', 'participle'=>'driven', 'gerund'=>'driving','meaning'=>'conducir'],
['verb'=>'eat', 'past'=>'ate', 'participle'=>'eaten', 'gerund'=>'eating','meaning'=>'comer'],
['verb'=>'fall', 'past'=>'fell', 'participle'=>'fallen', 'gerund'=>'falling','meaning'=>'caer'],
['verb'=>'forget', 'past'=>'forgot', 'participle'=>'forgotten', 'gerund'=>'forgetting','meaning'=>'olvidar'],
['verb'=>'forgive', 'past'=>'forgave', 'participle'=>'forgiven', 'gerund'=>'forgiving','meaning'=>'perdonar'],
['verb'=>'freeze', 'past'=>'froze', 'participle'=>'frozen', 'gerund'=>'freezing','meaning'=>'helar'],
['verb'=>'get', 'past'=>'got', 'participle'=>'gotten', 'gerund'=>'getting','meaning'=>'conseguir'],
['verb'=>'give', 'past'=>'gave', 'participle'=>'given', 'gerund'=>'giving','meaning'=>'dar'],
['verb'=>'hide', 'past'=>'hid', 'participle'=>'hidden', 'gerund'=>'hiding','meaning'=>'esconder'],
['verb'=>'ride', 'past'=>'rode', 'participle'=>'ridden', 'gerund'=>'riding','meaning'=>'cabalgar'],
['verb'=>'shake', 'past'=>'shook', 'participle'=>'shaken', 'gerund'=>'shaking','meaning'=>'agitar'],
['verb'=>'speak', 'past'=>'spoke', 'participle'=>'spoken', 'gerund'=>'speaking','meaning'=>'hablar'],
['verb'=>'steal', 'past'=>'stole', 'participle'=>'stolen', 'gerund'=>'stealing','meaning'=>'robar'],
['verb'=>'take', 'past'=>'took', 'participle'=>'taken', 'gerund'=>'taking','meaning'=>'tomar'],
['verb'=>'wake up', 'past'=>'woke up', 'participle'=>'woken up', 'gerund'=>'waking up','meaning'=>'despertar'],
['verb'=>'write', 'past'=>'wrote', 'participle'=>'written', 'gerund'=>'writin','meaning'=>'escribir'],
['verb'=>'arise', 'past'=>'arose', 'participle'=>'arisen', 'gerund'=>'arising','meaning'=>'levantarse'],
['verb'=>'awake', 'past'=>'awoke', 'participle'=>'awoken', 'gerund'=>'awaking','meaning'=>'despertar'],
['verb'=>'beat', 'past'=>'beat', 'participle'=>'beaten', 'gerund'=>'beating','meaning'=>'golpear'],
['verb'=>'build', 'past'=>'built', 'participle'=>'built', 'gerund'=>'building','meaning'=>'construir'],
['verb'=>'dream', 'past'=>'dreamt', 'participle'=>'dreamt', 'gerund'=>'dreaming','meaning'=>'soñar'],
['verb'=>'feed', 'past'=>'fed', 'participle'=>'fed', 'gerund'=>'feeding','meaning'=>'alimentar'],
['verb'=>'feel', 'past'=>'felt', 'participle'=>'felt', 'gerund'=>'feeling','meaning'=>'sentir'],
['verb'=>'find', 'past'=>'found', 'participle'=>'found', 'gerund'=>'finding','meaning'=>'encontrar'],
['verb'=>'hang', 'past'=>'hung', 'participle'=>'ung', 'gerund'=>'hanging','meaning'=>'colgar'],
['verb'=>'have', 'past'=>'had', 'participle'=>'had', 'gerund'=>'having','meaning'=>'tener'],
['verb'=>'hear', 'past'=>'heard', 'participle'=>'heard', 'gerund'=>'hearing','meaning'=>'escuchar'],
['verb'=>'hold', 'past'=>'held', 'participle'=>'held', 'gerund'=>'holding','meaning'=>'sostener'],
['verb'=>'keep', 'past'=>'kept', 'participle'=>'kept', 'gerund'=>'keeping','meaning'=>'guardar'],
['verb'=>'lead', 'past'=>'led', 'participle'=>'led', 'gerund'=>'leading','meaning'=>'guiar'],
['verb'=>'leave', 'past'=>'left', 'participle'=>'left', 'gerund'=>'leaving','meaning'=>'abandonar'],
['verb'=>'lend', 'past'=>'lent', 'participle'=>'lent', 'gerund'=>'lending','meaning'=>'prestar'],
['verb'=>'light', 'past'=>'lit', 'participle'=>'lit', 'gerund'=>'lighting','meaning'=>'encender'],
['verb'=>'lose', 'past'=>'lost', 'participle'=>'lost', 'gerund'=>'losing','meaning'=>'perder'],
['verb'=>'make', 'past'=>'made', 'participle'=>'made', 'gerund'=>'making','meaning'=>'hacer'],
['verb'=>'mean', 'past'=>'meant', 'participle'=>'meant', 'gerund'=>'meaning','meaning'=>'significar'],
['verb'=>'meet', 'past'=>'met', 'participle'=>'met', 'gerund'=>'meeting','meaning'=>'conocer'],
['verb'=>'pay', 'past'=>'paid', 'participle'=>'paid', 'gerund'=>'paying','meaning'=>'pagar'],
['verb'=>'read', 'past'=>'read', 'participle'=>'read', 'gerund'=>'reading','meaning'=>'leer'],
['verb'=>'say', 'past'=>'said', 'participle'=>'said', 'gerund'=>'saying','meaning'=>'decir'],
['verb'=>'sell', 'past'=>'sold', 'participle'=>'sold', 'gerund'=>'selling','meaning'=>'vender'],
['verb'=>'send', 'past'=>'sent', 'participle'=>'sent', 'gerund'=>'sending','meaning'=>'enviar'],
['verb'=>'shoot', 'past'=>'shot', 'participle'=>'shot', 'gerund'=>'shooting','meaning'=>'disparar'],
['verb'=>'sit', 'past'=>'sat', 'participle'=>'sat', 'gerund'=>'sitting','meaning'=>'sentar'],
['verb'=>'sleep', 'past'=>'slept', 'participle'=>'slept', 'gerund'=>'sleeping','meaning'=>'dormir'],
['verb'=>'spend', 'past'=>'spent', 'participle'=>'spent', 'gerund'=>'spending','meaning'=>'gastar'],
['verb'=>'stand', 'past'=>'stood', 'participle'=>'stood', 'gerund'=>'standing','meaning'=>'estar de pie'],
['verb'=>'sweep', 'past'=>'swept', 'participle'=>'swept', 'gerund'=>'sweeping','meaning'=>'barrer'],
['verb'=>'tell', 'past'=>'told', 'participle'=>'told', 'gerund'=>'telling','meaning'=>'decir'],
['verb'=>'understand', 'past'=>'understood', 'participle'=>'understood', 'gerund'=>'understanding','meaning'=>'entender'],
['verb'=>'win', 'past'=>'won', 'participle'=>'won', 'gerund'=>'winning','meaning'=>'ganar'],
['verb'=>'wind', 'past'=>'wound', 'participle'=>'wound', 'gerund'=>'winding','meaning'=>'hacer girar'],
['verb'=>'cling', 'past'=>'clung', 'participle'=>'clung', 'gerund'=>'clinging','meaning'=>'agarrarse'],
['verb'=>'creep', 'past'=>'crept', 'participle'=>'crept', 'gerund'=>'creeping','meaning'=>'arrastrarse'],
['verb'=>'deal', 'past'=>'dealt', 'participle'=>'dealt', 'gerund'=>'dealing','meaning'=>'repartir'],
['verb'=>'be', 'past'=>'was/were', 'participle'=>'been', 'gerund'=>'being','meaning'=>'ser/estar'],
['verb'=>'do', 'past'=>'did', 'participle'=>'done', 'gerund'=>'doing','meaning'=>'hacer'],
['verb'=>'go', 'past'=>'went', 'participle'=>'gone', 'gerund'=>'going','meaning'=>'ir'],
['verb'=>'see', 'past'=>'saw', 'participle'=>'seen', 'gerund'=>'seeing','meaning'=>'ver'],
['verb'=>'sew', 'past'=>'sewed', 'participle'=>'sewn', 'gerund'=>'sewing','meaning'=>'coser'],
['verb'=>'wear', 'past'=>'wore', 'participle'=>'worn', 'gerund'=>'wearing','meaning'=>'usar'],
['verb'=>'bear', 'past'=>'bore', 'participle'=>'born', 'gerund'=>'bearing','meaning'=>'tolerar']
        ]);
    }
}
